name = "namechart"
main = "src/index.js"
compatibility_date = "2026-07-01"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "namechart"
database_id = "6f658ccd-7d51-4de7-8eb7-b643fc1a4e97"

[triggers]
crons = ["0 9 * * 1"]

[vars]
INDEXNOW_KEY = "2913dae48d02d63b78ce1b2daf0bb420"

[observability]
enabled = true
